[general]
working_directory = "C:/Users/anas/dev"
live_config_reload = true

[bell]
animation = "Linear"
duration = 500
color = "#b59b9c"

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
bold = { family = "FiraMono Nerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font", style = "Bold Italic" }
size = 18
offset = { x = 0, y = 1 }

[window]
dynamic_padding = false
opacity = 0.9
title = "Terminal"
startup_mode = "Maximized"

[scrolling]
history = 0

[terminal]
shell = { program = "nu.exe", args = [] }
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true


[colors]
[colors.primary]
background = "0x191622"
foreground = "0xe1e1e6"

[colors.cursor]
text = "0x191622"
cursor = "0xf8f8f2"

[colors.normal]
black = "0x000000"
red = "0xff5555"
green = "0x50fa7b"
yellow = "0xeffa78"
blue = "0xbd93f9"
magenta = "0xff79c6"
cyan = "0x8d79ba"
white = "0xbfbfbf"

[colors.bright]
black = "0x4d4d4d"
red = "0xff6e67"
green = "0x5af78e"
yellow = "0xeaf08d"
blue = "0xcaa9fa"
magenta = "0xff92d0"
cyan = "0xaa91e3"
white = "0xe6e6e6"

[colors.dim]
black = "0x000000"
red = "0xa90000"
green = "0x049f2b"
yellow = "0xa3b106"
blue = "0x530aba"
magenta = "0xbb006b"
cyan = "0x433364"
white = "0x5f5f5f"